name: Rust CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Build
        run: cargo build --tests --workspace

      - name: Test
        run: cargo test --workspace
